client/src/components/Navbar.js

fix naming for navbar

---

client/src/SASS/UserProfile.scss
client/src/components/UserProfile_LI.js
client/src/components/UserProfile_Tabs.js

- [ X] New feature (non-breaking change which adds functionality)

Update to Style. Wrap projects in Link

---

client/src/components/Project.js
client/src/components/ReduxTestComponent.js

squash errors

---

client/src/SASS/Project.scss
client/src/SASS/TopBar.scss

Fixed margin on project component and gave height to topbar component

Fixed margin on project component and gave height to topbar component

---

client/src/SASS/OnboardingForm.scss

Fixes CSS spill-out issue from yesterday

Wrapped all form elements in OnboardingForm scss

---

client/src/App.js
client/src/components/OnboardingForm.js
client/src/store/actions/usersActions.js
client/src/store/reducers/projectsReducer.js

hotfix to new backend data structures

---

client/src/App.js
client/src/SASS/Navbar.scss
client/src/components/Loggedin.js
client/src/components/Project.js
client/src/components/UserProfile_LI.js
client/src/components/UserProfile_Tabs.js
client/src/store/actions/index.js
client/src/store/reducers/projectsReducer.js

Redux incorp. project and profile comp.

---

client/src/App.js
client/src/components/OnboardingForm/OnboardingForm.js
client/src/store/actions/usersActions.js
client/src/store/reducers/usersReducer.js

fix data handling on usersActions
adjust routing to & from OnboardingForm

adjust data handling, fix routing and state updates

---

client/src/App.js

add if statement to useEffect to prevent server errors

---

client/src/App.js
client/src/auth-wrapper.js
client/src/components/OnboardingForm/OnboardingForm.js
client/src/components/OnboardingForm/Step2.js

Can upload avatar images to s3 and save to user in db

Avatar image uploading working

---

client/src/components/ImageViewer/ImageViewer.js
client/src/components/Project.js

ImageViewer for project 17 is functional

---

client/src/DesignHub.js
client/src/SASS/Project.scss
client/src/components/AddProject.js
client/src/components/EditProject.js
client/src/components/OnboardingForm/OnboardingForm.js
client/src/components/Project.js
client/src/components/ProjectForm.js

EditProject form is working

---

client/src/components/ProjectForm.js

Got mainImg on projects to work

---

client/src/components/Project.js

add loading to project.js

---

client/src/components/Project.js
client/src/components/UserProfile/UserProfile_Tabs.js

change fetch axios to env var

---

client/src/components/ProjectForm.js

cancel button goes back to previous page

---

client/src/SASS/Settings.scss
client/src/SASS/TopBar.scss

Changed profile pic thumbnail border radius to 100%

---

client/src/components/Project.js
client/src/components/UserProfile/UserProfile_LI.js

Took out staging

---

client/src/components/UserProfile/UserProfile_LI.js

Took out loading

---

client/src/SASS/ImageViewer.scss
client/src/SASS/OnboardingForm.scss
client/src/SASS/Project.scss
client/src/SASS/ProjectComments.scss
client/src/SASS/ProjectForm.scss
client/src/SASS/_mixins.scss
client/src/components/ImageViewer/ImageViewer.js
client/src/components/ImageViewer/ProjectComments.js

Contains styling bug fixes. 

---

client/src/SASS/StickyComment.scss

adjust z-index to fix comment-form display

---

client/src/SASS/OnboardingForm.scss
client/src/components/OnboardingForm/Step2.js

css from onboarding form was leaking out to projectform, solved by adjusting css naming

fix leaky css on thumbnails for image uploaders

---

client/src/components/Project.js

fix created by display on project header

---

client/src/SASS/ProjectForm.scss
client/src/components/Icons/DeleteIcon.js
client/src/components/Project.js
client/src/components/ProjectForm.js

Added modal to delete project, added delete functionality

---

client/src/components/ImageViewer/TempComment.js

enter key now submits sticky comment

---

client/src/SASS/ProjectForm.scss
client/src/SASS/_mixins.scss
client/src/components/OnboardingForm/Step1.js
client/src/components/OnboardingForm/Step2.js
client/src/components/ProjectForm.js

Fixed styling bugs

---

client/src/components/ImageViewer/ImageViewer.js
client/src/components/Project.js
client/src/components/ProjectForm.js

Delete project modal fixed

---

client/src/SASS/ProjectForm.scss
client/src/SASS/_mixins.scss

adjust responsive styles

---

client/src/SASS/Project.scss
client/src/SASS/ProjectComments.scss

solves issue where comment input gets hidden behind comment submit button

fix styling on projectComment input form

---

client/src/App.js
client/src/DesignHub.js
client/src/SASS/Settings.scss
client/src/components/Settings.js
client/src/components/Settings/Account.js
client/src/components/Settings/Privacy.js

Settings component

---

client/src/components/ProjectForm.js

replacer loader with loading component

---

client/src/SASS/LandingPage.scss

Landing page responsive styling

---

client/src/components/TopBar.js

logo links to profile temporarily

---

client/src/components/ImageViewer/ImageViewer.js
client/src/components/MultiImageUpload.js
client/src/components/Project.js
client/src/components/ProjectForm.js
client/src/components/UserProfile/UserProfile_Tabs.js

mainImg now changes  when images are deleted, updated or added

---

client/src/SASS/Heatmap.scss
client/src/SASS/Navbar.scss
client/src/SASS/UserProfile.scss
client/src/components/UserProfile/UserProfile_Tabs.js

Added breakpoints for bigger screens

---

client/src/SASS/UserProfile.scss
client/src/components/UserProfile/UserProfile_Tabs.js

Added the folder tab looking thing from design file to profile tabs

---

client/src/SASS/DesignHub.scss
client/src/SASS/UserProfile.scss

Fixed userprofile issues

---

client/src/SASS/SearchPage.scss
client/src/components/SearchPage.js
client/src/components/SearchUserCard.js

Search page styling

---

client/src/SASS/ProjectForm.scss
client/src/components/ProjectForm.js

alters form validation on ProjectForm, removes dead code

adjust form validation styles

---

client/src/DesignHub.js
client/src/components/UserProfile/UserProfile_LI.js

Fixes some bugs on profile

---

client/src/App.js
client/src/DesignHub.js
client/src/components/Navbar.js
client/src/components/UserProfile/UserProfile_LI.js
client/src/components/UserProfile/UserProfile_Tabs.js
client/src/store/actions/index.js
client/src/store/reducers/projectsReducer.js
client/src/store/reducers/starsReducer.js
client/src/store/reducers/usersReducer.js

Changed initialState of singleUser

---

client/src/SASS/ProjectComments.scss

Comments look good now

---

client/src/components/Icons/StarIcon.js
client/src/components/Project.js
client/src/store/actions/index.js
client/src/store/reducers/starsReducer.js

Made action and reducer for starStatus

---

client/src/components/Project.js
client/src/store/actions/index.js
client/src/store/reducers/starsReducer.js

Added unStar to Project.js

---

client/src/components/Project.js

Moved onClick to div

---

client/src/components/UserProfile/UserProfile_Tabs.js

set default img if length of projects arr is 0

---

client/src/components/UserProfile/UserProfile_LI.js

fix issue where clicking on different user does not cause a DOM repaint

---

client/src/SASS/Settings.scss
client/src/components/Settings.js

changes Link to NavLink, adds style for active class

fix link styles on settings page

---

client/src/SASS/SearchPage.scss
client/src/SASS/TopBar.scss
client/src/SASS/UserProfile.scss
client/src/components/TopBar.js

adds lightmode to followers component on profile page, search component, mobile navbar

add lightmode to followers, search, mobile nav

---

client/src/SASS/ProjectForm.scss
client/src/components/Icons/UploadCloud.js
client/src/components/MultiImageUpload.js

Adds styling to dropzone when active

---

client/src/SASS/Explore.scss
client/src/SASS/Navbar.scss
client/src/SASS/Notifications.scss
client/src/SASS/Project.scss
client/src/SASS/ProjectComments.scss
client/src/SASS/ProjectForm.scss
client/src/SASS/UserProfile.scss
client/src/components/Explore/ExploreTabs.js
client/src/components/Navbar.js
client/src/components/Notifications.js
client/src/components/UserProfile/UserProfile_LI.js
client/src/components/UserProfile/UserProfile_Tabs.js

fixed navbar dot

---

client/src/components/UserProfile/UserProfile_LI.js

fix followers update bug

---

client/src/components/ProjectForm.js

Delete Project button bug fixed

---

client/src/components/Explore/ExploreTabs.js

Uploaded Following Tab Variables

---

client/src/App.js
client/src/components/LandingPage.js
client/src/components/Navbar.js
client/src/components/Notifications.js
client/src/components/OnboardingForm/OnboardingForm.js
client/src/components/Settings.js
client/src/components/UserProfile/UserProfile_LI.js
client/src/components/UserProfile/UserProfile_Tabs.js
client/src/index.js
client/src/store/actions/usersActions.js

Console is clear!

---

client/src/components/Explore/ExploreTabs.js

Changed project.id to project.projectId

---

client/src/components/Explore/ExploreTabs.js

changed in the right place this time

---

client/src/SASS/_mixins.scss
client/src/SASS/_palette.scss
client/src/components/TopBar.js

adds documentation for theming function

add comments to theming code

---

client/src/utilities/axiosWithAuth.js

This PR maintains compatibility with the server after a major security update.

Security Update

---

client/package.json
client/src/SASS/TopBar.scss
client/src/components/TopBar.js
client/yarn.lock

final logout

---

client/src/components/ProjectForm.js

Edit form validation

---

client/src/SASS/Error401Projects.scss
client/src/SASS/Error404Projects.scss
client/src/SASS/ProjectForm.scss
client/src/components/Error401Projects.js
client/src/components/Error404Projects.js
client/src/components/Explore/ExploreTabs.js
client/src/components/Project.js
client/src/components/TopBar.js
client/src/components/UserProfile/UserProfile_LI.js
client/src/components/UserProfile/UserProfile_Tabs.js
client/src/store/actions/index.js
client/src/store/reducers/projectsReducer.js

Explore profile loading indicator

---

client/src/SASS/CharacterCount.scss
client/src/SASS/ProjectForm.scss
client/src/SASS/UserProfile.scss
client/src/components/CharacterCount.js
client/src/components/OnboardingForm/Step1.js
client/src/components/ProjectForm.js
client/src/components/Settings/Account.js

Improved form ux

---

client/src/DesignHub.js
client/src/SASS/TopBar.scss
client/src/components/TopBar.js

Fixes the following issues with the user info tooltip:
1) Now adapts to the theme of the app (dark or light mode)
2) Reacts to clicks outside of the area
3) Adjusted click zone
4) Added a 'My Profile' button
5) Re-arranged buttons for intuity
6) Username text now adapts to theme of the app (dark or light mode)
7) Buttons now use react router instead of window global object, so app can now retain state again
Switching between dark light mode, testing the buttons in the tooltip

Fix tooltip

---

client/src/SASS/DesignHub.scss
client/src/SASS/Explore.scss
client/src/SASS/TopBar.scss
client/src/components/Explore/Explore.js
client/src/components/Explore/ExploreTabs.js

Fixes # Explore page design
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] Complete, but not tested (may need new tests)

Explore page

---

client/src/SASS/ProjectForm.scss
client/src/components/ProjectForm.js
client/src/components/Settings/Account.js

Co-authored-by: rogermcconkiejr <roger.mcconkiejr@gmail.com>

added charactercount to other inputs in form

---

client/src/App.scss
client/src/SASS/Error401Projects.scss
client/src/SASS/Error404Projects.scss
client/src/components/Error401Projects.js
client/src/components/Error404Projects.js

Not found page projects

---

client/src/SASS/Explore.scss

fixed explore

---

client/src/SASS/UserProfile.scss
client/src/components/UserProfile/UserProfile_Tabs.js

reverted profile page to how it use to look

---

client/src/SASS/ProjectForm.scss
client/src/components/UserProfile/UserProfile_Tabs.js

Collaborators tab fix

---

client/.eslintrc.js
client/package.json
client/src/__tests__/__snapshots__/ProjectForm.test.js.snap
client/src/__tests__/__snapshots__/SearchBar.test.js.snap
client/src/__tests__/__snapshots__/SearchPage.test.js.snap
client/src/components/SearchBar.js
client/yarn.lock

Set up esint

---

codeclimate.yml

Fixed typo on code climate configuration file
Added underscores to snapshots and tests

Code climate config

---

codeclimate.yml

Fixing another typo?

---

package.json

`yarn run local-coverage` will now run tests and show % of code reviewed by code climate.

Added script to test codeclimate coverage locally.

---

src/__tests__/App.test.js
src/__tests__/Heatmap.test.js
src/__tests__/LandingPage.test.js
src/__tests__/Loading.test.js
src/__tests__/NavBar.test.js
src/__tests__/Notifications.test.js
src/__tests__/ProjectForm.test.js
src/__tests__/SearchBar.test.js
src/__tests__/SearchPage.test.js
src/__tests__/SearchUserCard.test.js

Updated unit tests with the new file paths for components.
Broken tests

Fixed broken unit tests

---

.travis.yml

Added config to travisCI for CodeClimate.

Set up test coverage.

---

.travis.yml

added missing command

---

src/__tests__/App.test.js
src/__tests__/Heatmap.test.js
src/__tests__/LandingPage.test.js
src/__tests__/Loading.test.js
src/__tests__/NavBar.test.js
src/__tests__/Notifications.test.js
src/__tests__/ProjectForm.test.js
src/__tests__/SearchBar.test.js
src/__tests__/SearchPage.test.js
src/__tests__/SearchUserCard.test.js

Reverts Lambda-School-Labs/designhub-fe#193

Revert "Fixed broken unit tests"

---

src/views/ImageViewer/ImageWithComments.js
src/views/ImageViewer/ProjectComments.js
src/views/ImageViewer/postCommentNotification.js

Created a file to export `postCommentNotification` function to ImageWithComments.js and ProjectComments.js.
Duplicate functions on different components.

Move duplicated function into it's own file in ImageViewer folder.

---

.github/workflows/ci.yml
package.json
yarn.lock

Setup code climate test

---

.prettierrc.js
package.json

Adds common/Icons to the ignore for test coverage

Added common/Icons to collectCoverageFrom

---

.prettierrc.json

removed the prettierrc.json file

---

src/views/LandingPage/LandingPageNav.js

Created a file structure for new CRUD operations. 
Get requests are stored in `/querries`  
Create, Update, And Delete are stored in `./mutations`
**When reviewing this PR please check my added files against the `index.js` files in `/resolvers/Query` & `/resolvers/Mutation` on the backend repository.** I want to make sure I didn't miss anything and a 2nd set of eyes on this is helpful.

Added folders and files for Apollo-Client & formatted LandingPageNav.js

---

src/graphql/mutations/addProject.js
src/graphql/mutations/addProjectPhoto.js
src/graphql/mutations/addUser.js
src/graphql/mutations/deleteUser.js
src/graphql/mutations/updateUser.js
src/graphql/queries/project.js
src/graphql/queries/projectPhotos.js
src/graphql/queries/projectPhotosOne.js
src/graphql/queries/projectUser.js
src/graphql/queries/projects.js
src/graphql/queries/user.js
src/graphql/queries/users.js

Added user CRUD functions to `/graphql`

User CRUD added to /graphql

---

src/graphql/mutations/addPhotoComments.js
src/graphql/mutations/addProject.js
src/graphql/mutations/deleteHeatmap.js
src/graphql/mutations/deletePhotoComments.js
src/graphql/mutations/deleteUser.js
src/graphql/mutations/deleteUserResearch.js
src/graphql/mutations/updateCategory.js
src/graphql/mutations/updatePhotoComments.js
src/graphql/mutations/updateProject.js
src/graphql/queries/userById.js
src/views/Projects/Project.js
src/views/Projects/ProjectForm.js

Apollo client

---

.eslintrc.js
src/views/Explore/ExploreTabs.js
src/views/Explore/Following.js
src/views/Explore/Popular.js
src/views/Explore/Recent.js
src/views/Explore/Teams.js
src/views/Explore/styles.scss
src/views/Onboarding/Step1.js
src/views/Onboarding/Step2.js
src/views/Onboarding/index.js
src/views/Onboarding/styles.scss

- [X ] Complete, but not tested (may need new tests)

added tings

---

src/views/Explore/AllTab.js
src/views/Explore/Animation.js
src/views/Explore/ExploreTabs.js
src/views/Explore/GraphicDesign.js
src/views/Explore/Illustration.js
src/views/Explore/MotionDesign.js
src/views/Explore/ProductDesign.js
src/views/Explore/UIDesign.js
src/views/Explore/UXDesign.js
src/views/Explore/WebDesign.js
src/views/Explore/deleteme.js
src/views/Explore/index.js
src/views/Project/ProjectThumbnail.js

added some things to a branch

---

src/graphql/index.js
src/graphql/mutations/comments/addComments.js
src/graphql/mutations/comments/deleteComments.js
src/graphql/mutations/comments/updateComments.js
src/graphql/mutations/projects/addProject.js
src/graphql/mutations/projects/addProjectPhoto.js
src/graphql/mutations/projects/deleteProject.js
src/graphql/mutations/projects/deleteProjectPhoto.js
src/graphql/mutations/projects/updateProject.js
src/graphql/mutations/projects/updateProjectPhoto.js
src/graphql/mutations/users/addFollower.js
src/graphql/mutations/users/addUser.js
src/graphql/mutations/users/deleteFollower.js
src/graphql/mutations/users/deleteUser.js
src/graphql/mutations/users/updateUser.js
src/graphql/queries/projects/project.js
src/graphql/queries/projects/projects.js
src/graphql/queries/users/search.js
src/graphql/queries/users/users.js
src/views/Explore/index.js

Added queries and mutations files to /graphql.

Queries and mutations up to date with back-end

---

src/common/PrivateRoute/index.js

fix syntax error

---

src/App.js
src/common/Callback/index.js
src/common/Layout/index.js
src/common/Layout/styles.scss
src/common/Nav/LoginBar.js
src/common/Nav/TopBar.js
src/common/Nav/styles.scss
src/common/PrivateRoute/index.js
src/graphql/mutations/projects/addProject.js
src/graphql/mutations/projects/deleteProject.js
src/graphql/queries/projects/project.js
src/graphql/queries/projects/projects.js
src/graphql/queries/users/user.js
src/graphql/queries/users/users.js
src/index.js
src/utilities/auth-spa.js
src/views/Explore/AllTab.js
src/views/Explore/ExploreTabs.js
src/views/Explore/Illustration.js
src/views/Explore/index.js
src/views/Onboarding/OnboardingForm.js
src/views/Project/ProjectThumbnail.js

Onboarding 100% works with Auth0, LogInBar and TopBar now swap if user is logged in (done in Layout.js). Started pulling data into explore page. TopBar still needs searchBar hooked up.

Onboarding gql

---

src/common/Nav/TopBar.js
src/common/Nav/styles.scss
src/graphql/mutations/comments/deleteComments.js
src/graphql/queries/users/doesUserExist.js
src/views/Explore/AllTab.js
src/views/Onboarding/OnboardingForm.js

Added nav links to TopBar dropdown (desktop and mobile).
-Consolidates navigation by removing sidebar from app.
-Removed some unused code.

TopBar dropdown Nav

---

README.md

Added a weekly workflow outline to README.md

Added weekly workflow outline to README

---

package.json
src/App.js
src/common/Nav/LoginBar.js
src/utilities/auth-spa.js
src/views/Settings/Account.js
src/views/Settings/index.js
src/views/Settings/styles.scss
yarn.lock

User settings

---

src/views/CreateProject/ProjectFormBody.js
src/views/Explore/index.js
src/views/Project/ProjectThumbnail.js

243 bastian

---

src/App.js
src/common/Callback/index.js
src/common/Nav/LoginBar.js
src/common/Nav/TopBar.js
src/common/PrivateRoute/index.js
src/index.js
src/views/CreateProject/CaseStudy.js
src/views/CreateProject/Editing.js
src/views/CreateProject/Privacy.js
src/views/CreateProject/ProjectFormBody.js
src/views/CreateProject/ThumbnailContainer.js
src/views/CreateProject/index.js
src/views/Explore/WebDesign.js
src/views/Onboarding/OnboardingForm.js
src/views/Project/ImageViewer/ImageViewer.js
src/views/Project/ImageViewer/ImageWithComments.js
src/views/Project/ImageViewer/useWindowDimensions.js
src/views/Project/ProjectButtonLinks.js
src/views/Project/ProjectDetails.js
src/views/Project/ProjectPdf.js
src/views/Project/ProjectThumbnail.js
src/views/Project/index.js
src/views/Settings/Account.js
src/views/Settings/index.js

Fixed all warnings on console.
Fixes #257

Fixed all warnings for deployment.

---

src/graphql/mutations/projects/addProject.js
src/graphql/mutations/projects/updateProject.js
src/graphql/queries/projects/project.js
src/graphql/queries/projects/projects.js
src/index.js
src/views/CreateProject/ProjectFormBody.js
src/views/Explore/AllTab.js
src/views/Explore/ExploreTabs.js
src/views/Explore/Illustration.js
src/views/Project/ProjectThumbnail.js

fix env error on deployment

---

src/views/Explore/ExploreTabs.js
src/views/Explore/styles.scss

removed errors for deployment.

Remove error messages.

---

package.json
src/views/Profile/ProfileTabs.js
src/views/Profile/index.js
yarn.lock

Profile settings
